modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
issueTrackerURL="https://github.com/Mrthomas20121-Mods/BlockEffect/issues"

[[mods]]
modId="block_effect"
version="1.1.0"
displayName="Food Update"
displayURL="https://www.curseforge.com/minecraft/mc-mods/block_effect"
authors="Mrthomas20121"
description='''
Add effects to the player on block break.
'''